### ISSUE TITLE
integration with alfred

### ISSUE THREAD

**Issue by krist-jin** [scommab/d-fine#3]
[Alfred](https://www.alfredapp.com) is a cool Productivity App for Mac OS X. I think d-fine will be cooler for Mac guys if it is friendly with Alfred.

Alfred supports custom search tool, for example you can press command+space to wake up Alfred and if you enter "twitter WTF" in Alfred and press enter it will automatically open twitter and search WTF for you in twitter. The url pattern is like http:twitter.com/search?q={query}

So if d-fine can also have this patten of url, it will be great!

Hopefully this makes sense.

**Comment by scommab** [comment]
I haven't tried Alfred (it seems cool). But it looks like it can accept custom queries. So it should be adaptable to d-fine, by using http://<d-fine server>/#{query}
https://www.alfredapp.com/help/features/web-search/custom-searches/
